# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-17 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_address_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('content', models.TextField(max_length=5555, verbose_name='\u6c42\u8d2d\u4fe1\u606f')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.TheUser', verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u6211\u8981\u4e70',
                'verbose_name_plural': '\u6211\u8981\u4e70',
            },
        ),
    ]
