# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 09:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='\u4f18\u60e0\u7801')),
                ('valid_from', models.DateTimeField(verbose_name='\u751f\u6548\u65f6\u95f4')),
                ('valid_to', models.DateTimeField(verbose_name='\u8fc7\u671f\u65f6\u95f4')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='\u6298\u6263\u7387')),
                ('active', models.BooleanField(verbose_name='\u662f\u5426\u6fc0\u6d3b')),
            ],
        ),
    ]
