# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-13 04:47
from __future__ import unicode_literals

from django.db import migrations
import shop.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20170713_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='order',
            field=shop.fields.OrderField(blank=True, verbose_name='\u6392\u5e8f'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='order',
            field=shop.fields.OrderField(blank=True, verbose_name='\u6392\u5e8f'),
        ),
    ]
