# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-13 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20170713_1622'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
