# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-15 01:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u5c5e\u6027\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u5c5e\u6027',
                'verbose_name_plural': '\u5c5e\u6027',
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='conment',
            name='name',
        ),
        migrations.AddField(
            model_name='conment',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True, default=0, verbose_name='\u8bc4\u8bba\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conment',
            name='goods_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.Goods', verbose_name='\u5546\u54c1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4'),
        ),
    ]
