# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-15 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20170715_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='goods_id',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
