# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-15 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20170715_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='option_value',
            field=models.CharField(default=0, max_length=5555, verbose_name='\u5c5e\u6027\u503c'),
            preserve_default=False,
        ),
    ]
