# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-17 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_attribute_option_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsAttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_value', models.CharField(max_length=255, verbose_name='\u5c5e\u6027\u503c')),
                ('attribute_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u5c5e\u6027\u4ef7\u683c')),
                ('attribute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Attribute', verbose_name='\u5546\u54c1\u5c5e\u6027')),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Goods', verbose_name='\u5546\u54c1')),
            ],
            options={
                'verbose_name': '\u5c5e\u6027\u503c',
                'verbose_name_plural': '\u5c5e\u6027\u503c',
            },
        ),
    ]
