# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-18 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_goodsattributevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_sale_number',
            field=models.BigIntegerField(editable=False, verbose_name='\u9500\u552e\u91cf'),
        ),
    ]
