# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-14 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2555, verbose_name='\u534f\u8bae\u5185\u5bb9')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u534f\u8bae',
                'verbose_name_plural': '\u534f\u8bae',
            },
        ),
    ]
