# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-14 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255, verbose_name='\u7248\u672c\u53f7')),
                ('content', models.TextField(max_length=5555, verbose_name='\u66f4\u65b0\u5185\u5bb9')),
                ('url', models.URLField(max_length=255, verbose_name='\u4e0b\u8f7d\u7f51\u5740')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7248\u672c',
            },
        ),
    ]
