# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-15 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'verbose_name': '\u7248\u672c', 'verbose_name_plural': '\u7248\u672c'},
        ),
    ]
