# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-18 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='buy_number',
            field=models.IntegerField(max_length=255, verbose_name='\u8d2d\u4e70\u6570\u91cf'),
        ),
    ]
