# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-13 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_host_administrator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessrecord',
            options={'verbose_name': 'Access Record \u8bb0\u5f55', 'verbose_name_plural': 'Access Record \u8bb0\u5f55'},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name': 'Host\u4e3b\u4eba', 'verbose_name_plural': 'Host\u4e3b\u4eba'},
        ),
        migrations.AlterModelOptions(
            name='hostgroup',
            options={'verbose_name': 'Host Group \u7528\u6237\u7ec4', 'verbose_name_plural': 'Host Group \u7528\u6237\u7ec4'},
        ),
        migrations.AlterModelOptions(
            name='maintainlog',
            options={'verbose_name': 'Maintain Log\u65e5\u5fd7', 'verbose_name_plural': 'Maintain Log\u65e5\u5fd7'},
        ),
        migrations.AlterField(
            model_name='host',
            name='cpu',
            field=models.CharField(max_length=64, verbose_name=b'cpu'),
        ),
        migrations.AlterField(
            model_name='host',
            name='create_time',
            field=models.DateField(verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xa5\xe6\x9c\x9f'),
        ),
        migrations.AlterField(
            model_name='host',
            name='internal_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name=b'\xe4\xba\x92\xe8\x81\x94\xe7\xbd\x91ip'),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name=b'ip\xe5\x9c\xb0\xe5\x9d\x80'),
        ),
        migrations.AlterField(
            model_name='host',
            name='model',
            field=models.CharField(max_length=64, verbose_name=b'\xe6\xa8\xa1\xe5\x9e\x8b'),
        ),
        migrations.AlterField(
            model_name='host',
            name='nagios_name',
            field=models.CharField(blank=True, default=0, max_length=64, verbose_name='Nagios Host ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(max_length=64, verbose_name=b'\xe5\xa7\x93\xe5\x90\x8d'),
        ),
        migrations.AlterField(
            model_name='host',
            name='password',
            field=models.CharField(max_length=128, verbose_name=b'\xe5\xaf\x86\xe7\xa0\x81'),
        ),
        migrations.AlterField(
            model_name='host',
            name='ssh_port',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'ssh\xe7\xab\xaf\xe5\x8f\xa3'),
        ),
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Normal'), (1, 'Down'), (2, 'No Connect'), (3, 'Error')], verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81'),
        ),
        migrations.AlterField(
            model_name='host',
            name='user',
            field=models.CharField(max_length=64, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='address',
            field=models.CharField(max_length=128, verbose_name=b'\xe5\x9c\xb0\xe5\x9d\x80'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='contact',
            field=models.CharField(max_length=32, verbose_name=b'\xe8\x81\x94\xe7\xb3\xbb\xe4\xba\xba'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='create_time',
            field=models.DateField(auto_now=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xa5\xe6\x9c\x9f'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='customer_id',
            field=models.CharField(max_length=128, verbose_name=b'\xe6\xb6\x88\xe8\xb4\xb9\xe8\x80\x85id'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='description',
            field=models.TextField(verbose_name=b'\xe6\x8f\x8f\xe8\xbf\xb0'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='name',
            field=models.CharField(max_length=64, verbose_name=b'\xe5\xa7\x93\xe5\x90\x8d'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='telphone',
            field=models.CharField(max_length=32, verbose_name=b'\xe7\x94\xb5\xe8\xaf\x9d'),
        ),
    ]
