# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-17 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignee_address', models.CharField(max_length=5555, verbose_name='\u6536\u8d27\u4eba\u5730\u5740')),
                ('consignee_telphone', models.CharField(max_length=255, verbose_name='\u624b\u673a\u53f7')),
                ('consignee_name', models.CharField(max_length=255, verbose_name='\u6536\u8d27\u4eba\u59d3\u540d')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5730\u5740\u7ba1\u7406',
                'verbose_name_plural': '\u5730\u5740\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='TheUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=555, verbose_name='\u6635\u79f0')),
                ('phone', models.CharField(max_length=255, verbose_name='\u624b\u673a\u53f7')),
                ('password', models.CharField(max_length=555, verbose_name='\u5bc6\u7801')),
                ('real_name', models.CharField(max_length=255, verbose_name='\u771f\u5b9e\u59d3\u540d')),
                ('bank_card', models.CharField(max_length=555, verbose_name='\u94f6\u884c\u5361')),
                ('sex', models.CharField(choices=[('1', '\u7537'), ('0', '\u5973')], default=0, max_length=255, verbose_name='\u6027\u522b')),
                ('age', models.SmallIntegerField(default=0, verbose_name='\u5e74\u9f84')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='\u6ce8\u518c\u65f6\u95f4')),
                ('logo', models.ImageField(upload_to='images/userlogo', verbose_name='\u5934\u50cf')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u7ba1\u7406',
                'verbose_name_plural': '\u7528\u6237\u7ba1\u7406',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.TheUser', verbose_name='\u7528\u6237'),
        ),
    ]
