# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-17 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_theuser_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user_id',
        ),
        migrations.AddField(
            model_name='theuser',
            name='logo',
            field=models.ImageField(default=0, upload_to='images/userlogo', verbose_name='\u5934\u50cf'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
