# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-18 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20170718_0952'),
        ('users', '0007_address_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=5555, verbose_name='\u5546\u54c1\u540d\u79f0')),
                ('goods_price', models.CharField(max_length=255, verbose_name='\u5546\u54c1\u4ef7\u683c')),
                ('market_price', models.CharField(max_length=255, verbose_name='\u5e02\u573a\u4ef7')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='\u6536\u85cf\u65f6\u95f4')),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Goods', verbose_name='\u5546\u54c1')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.TheUser', verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u6536\u85cf\u7ba1\u7406',
                'verbose_name_plural': '\u6536\u85cf\u7ba1\u7406',
            },
        ),
    ]
