# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u5546\u54c1\u540d\u79f0')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': '\u5546\u54c1\u540d\u79f0',
                'verbose_name_plural': '\u5546\u54c1\u540d\u79f0',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='\u540d\u79f0')),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='\u56fe\u7247')),
                ('description', models.TextField(blank=True, verbose_name='\u4ea7\u54c1\u63cf\u8ff0')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u4ef7\u683c')),
                ('stock', models.PositiveSmallIntegerField(verbose_name='\u5e93\u5b58')),
                ('available', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u8d2d\u4e70')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.Category', verbose_name='\u5206\u7c7b')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=set([('id', 'slug')]),
        ),
    ]
