# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0003_auto_20170614_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='\u59d3')),
                ('last_name', models.CharField(max_length=50, verbose_name='\u540d')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
                ('address', models.CharField(max_length=250, verbose_name='\u5730\u5740')),
                ('postal_code', models.CharField(max_length=20, verbose_name='\u90ae\u653f\u7f16\u7801')),
                ('city', models.CharField(max_length=100, verbose_name='\u57ce\u5e02')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('paid', models.BooleanField(default=False, verbose_name='\u662f\u5426\u652f\u4ed8')),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name': '\u8ba2\u5355',
                'verbose_name_plural': '\u8ba2\u5355',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u4ef7\u683c')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='\u6570\u91cf')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order', verbose_name='\u8ba2\u5355')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.Product', verbose_name='\u5546\u54c1')),
            ],
            options={
                'verbose_name': '\u7269\u54c1',
                'verbose_name_plural': '\u7269\u54c1',
            },
        ),
    ]
