# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courese', '0004_auto_20170620_1037'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercourse',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='ordercourse',
            name='course_name',
        ),
        migrations.AddField(
            model_name='ordercourse',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='courese.Course', verbose_name='\u8bfe\u7a0b'),
            preserve_default=False,
        ),
    ]
