# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-29 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20170620_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=250, verbose_name='\u5bc6\u7801')),
            ],
            options={
                'verbose_name': '\u6ce8\u518c',
                'verbose_name_plural': '\u6ce8\u518c',
            },
        ),
    ]
