# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-17 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import picture.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0016_goodsattributevalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/ScrollView', verbose_name='\u56fe\u7247')),
                ('adversitation_position', models.CharField(choices=[(0, '\u56de\u8d2d\u533a\u8f6e\u64ad\u56fe'), (1, '\u9996\u9875\u63a8\u83503'), (2, '\u9996\u9875\u63a8\u83502'), (3, '\u9996\u9875\u63a8\u83501'), (4, '\u9996\u9875\u8f6e\u64ad\u56fe')], max_length=255, verbose_name='\u8f6e\u64ad\u56fe\u4f4d\u7f6e')),
                ('is_show', models.CharField(choices=[(1, '\u662f'), (0, '\u5426')], max_length=255, verbose_name='\u662f\u5426\u663e\u793a')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('order', picture.fields.OrderField(blank=True)),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Goods', verbose_name='\u5546\u54c1')),
            ],
            options={
                'verbose_name': '\u56fe\u7247\u7ba1\u7406',
                'verbose_name_plural': '\u56fe\u7247\u7ba1\u7406',
            },
        ),
    ]
