# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 04:42
from __future__ import unicode_literals

import courese.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courese', '0002_auto_20170616_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order'], 'verbose_name': '\u5185\u5bb9', 'verbose_name_plural': '\u5185\u5bb9'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'verbose_name': '\u6a21\u5757\u5927\u7ae0\u8282', 'verbose_name_plural': '\u6a21\u5757\u5927\u7ae0\u8282'},
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=courese.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=courese.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, verbose_name='\u5927\u7ae0\u8282\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=200, verbose_name='\u5927\u7ae0\u8282\u6807\u9898'),
        ),
    ]
