# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-05 02:49
from __future__ import unicode_literals

import courese.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courese', '0004_auto_20170620_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': '\u6587\u4ef6', 'verbose_name_plural': '\u6587\u4ef6'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': '\u56fe\u7247', 'verbose_name_plural': '\u56fe\u7247'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'verbose_name': '\u8bfe\u7a0b\u7ba1\u7406\u7684\u6a21\u5757(\u90e8\u5206)', 'verbose_name_plural': '\u8bfe\u7a0b\u7ba1\u7406\u7684\u6a21\u5757(\u90e8\u5206)'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name': '\u6587\u672c', 'verbose_name_plural': '\u6587\u672c'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': '\u89c6\u9891', 'verbose_name_plural': '\u89c6\u9891'},
        ),
        migrations.AddField(
            model_name='content',
            name='content',
            field=models.CharField(blank=True, max_length=2000, verbose_name='\u4e3a(\u6587\u672c,\u56fe\u7247,\u89c6\u9891,\u6587\u4ef6)\u6dfb\u52a0\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='content',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courese.Module', verbose_name='\u6a21\u5757(\u90e8\u5206)'),
        ),
        migrations.AlterField(
            model_name='content',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='\u6709\u5173\u8054\u5bf9\u8c61\u5173\u952e\u5b57'),
        ),
        migrations.AlterField(
            model_name='content',
            name='order',
            field=courese.fields.OrderField(blank=True, verbose_name='\u6b21\u5e8f(\u81ea\u5b9a\u4e49\u6a21\u578b\u5b57\u6bb5\u6392\u5e8f\u7528)'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, verbose_name='\u6a21\u5757(\u90e8\u5206)\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=200, verbose_name='\u6a21\u5757(\u90e8\u5206)\u6807\u9898'),
        ),
    ]
