# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-07 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courese', '0005_auto_20170705_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='module',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='file_related', to='courese.Module', verbose_name='\u521b\u5efa\u4eba'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='module',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='image_related', to='courese.Module', verbose_name='\u521b\u5efa\u4eba'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='module',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='text_related', to='courese.Module', verbose_name='\u521b\u5efa\u4eba'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='module',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='video_related', to='courese.Module', verbose_name='\u521b\u5efa\u4eba'),
            preserve_default=False,
        ),
    ]
